name: Build and run tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: builded_tests
        path: /home/runner/output

  run_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: get builded tests project
      uses: actions/download-artifact@v2
      with:
        name: builded_tests
        path: /home/runner/output
    - name: where are we
      run: pwd
    - name: Test
      run: dotnet test --no-build